name: Component Cookiecutter Test
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job test an example
    steps:
      - name: test example step
        id: start-test
        uses: actions/github-ci-actions@v1
        with:
          test: one
      # Use the output from the `hello` step
      - name: Get the completion status
        run: echo "The completion status was ${{ steps.hello.outputs.completed }}"
