name: Integration Tests

on: [pull_request, push]

jobs:
  integration_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        fprime-version: [1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: clone fprime
        run: |
          git clone -b v${{ matrix.fprime-version }} https://github.com/nasa/fprime.git
      - name: Test generation and building
        run: |
          cd fprime/Ref
          fprime-util generate
          fprime-util build