name: Build Package
on:
  release:
    types: [published]
jobs:
  Build-PyPI-Package:
    runs-on: ubuntu-latest
    steps:
    - name: "CheckoutÂ Repository"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Test PyPI
      uses: fprime-community/publish-pypi@main
      env:
        TWINE_PASSWORD: ${{ secrets.TESTPYPI_CREDENTIAL }}
      with:
        package: "fprime-tools"
    - name: PyPI
      uses: fprime-community/publish-pypi@main
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_CREDENTIAL }}
      with:
        repo: "pypi"
        package: "fprime-tools"
